sudo: required
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
install:
 - curl --insecure https://www.jpm4j.org/install/script | sudo sh
 - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
script:
 - mvn test
 - mvn clean package
after_success:
 - codacy-coverage-reporter -l Java -r ./target/site/jacoco/jacoco.xml